### ISSUE TITLE
Issue about 'int' object is not iterable

### ISSUE THREAD

**Issue by Zzzzy411** [avinashpaliwal/Super-SloMo#10]
I have solved this problem. Thanks.

**Comment by kimcaprio** [comment]
Hello,
Thank you for sharing you idea for us. I followed your code but I have a problem when I ran it on Linux OS.
It make an error message 'AttributeError: module 'ctypes' has no attribute 'windll'' when I ran python video_to_slomo.py.
Please let me know what's the matter with it?
Regars,

**Comment by Bumki-Kim** [comment]
I also have same problem that is 'AttributeError: module 'ctypes' has no attribute 'windll' as like kimcaprio. I also ran it on Linux OS.

**Comment by Bumki-Kim** [comment]
> Hello,
> Thank you for sharing you idea for us. I followed your code but I have a problem when I ran it on Linux OS.
> It make an error message 'AttributeError: module 'ctypes' has no attribute 'windll'' when I ran python video_to_slomo.py.
> Please let me know what's the matter with it?
> Regars,

I also have same problem that is 'AttributeError: module 'ctypes' has no attribute 'windll' as like kimcaprio. I also ran it on Linux OS.

**Comment by Zzzzy411** [comment]
> @Zzzzy411 How can fix 'int' object is not iterable issue? Can you tell me it please?

You have to change the codes in the API '_pil_loader' of dataloader.py.  
----------------------------------------------
  with open(path, 'rb') as f:
        img = Image.open(f)
        # Resize image if specified.
        if (resizeDim != None): 
            resized_img = img.resize(resizeDim, Image.ANTIALIAS)
        else:
            resized_img = img
        # Crop image if crop area specified.
        if (cropArea != None):
            cropped_img = img.crop(cropArea)
        else:
            cropped_img = resized_img
        # Flip image horizontally if specified.
        if frameFlip:
            flipped_img = cropped_img.transpose(Image.FLIP_LEFT_RIGHT)  
        else:
            flipped_img = cropped_img
        return flipped_img.convert('RGB')
----------------------------------------------
 Then you can solve this issue.

**Comment by ZhangXi19930818** [comment]
> Hello,
> Thank you for sharing you idea for us. I followed your code but I have a problem when I ran it on Linux OS.
> It make an error message 'AttributeError: module 'ctypes' has no attribute 'windll'' when I ran python video_to_slomo.py.
> Please let me know what's the matter with it?
> Regars,

To solve the error 'AttributeError: module 'ctypes' has no attribute 'windll'' in Linux, you just need to comment out the line in the 'video_to_slomo.py':
`ctypes.windll.kernel32.SetFileAttributesW(extractionDir, FILE_ATTRIBUTE_HIDDEN)`
This works for me.

**Comment by Bumki-Kim** [comment]
> > Hello,
> > Thank you for sharing you idea for us. I followed your code but I have a problem when I ran it on Linux OS.
> > It make an error message 'AttributeError: module 'ctypes' has no attribute 'windll'' when I ran python video_to_slomo.py.
> > Please let me know what's the matter with it?
> > Regars,
> 
> To solve the error 'AttributeError: module 'ctypes' has no attribute 'windll'' in Linux, you just need to comment out the line in the 'video_to_slomo.py':
> `ctypes.windll.kernel32.SetFileAttributesW(extractionDir, FILE_ATTRIBUTE_HIDDEN)`
> This works for me.

Thank you! This works for me!
