### ISSUE TITLE
Convert .pytorch model to .ckpt?

### ISSUE THREAD

**Issue by deama** [avinashpaliwal/Super-SloMo#15]
I was wondering if there is a .ckpt version available of the "SepConv - L_F" model, or perhaps if there is a way to convert the .pytorch model to a .ckpt one?

**Comment by avinashpaliwal** [comment]
`.ckpt` is just an extension used to save the model, you can use `.pth` as well. I think as long as the checkpoint was created using the `torch.save()`, you can load it back using `torch.load()`.

**Comment by deama** [comment]
So if I change "network-lf.pytorch" to "network-lf.ckpt" it should work?

**Comment by avinashpaliwal** [comment]
There is no need to rename the file. Looking at his code [here](https://github.com/sniklaus/pytorch-sepconv/blob/26b411e7776c444303e667d128ab0ad14a8439c2/run.py#L121), you can load the checkpoint like this:
```bash
model.load_state_dict(torch.load('checkpointName.pytorch'))
```

**Comment by deama** [comment]
Sorry, where do I put that?

**Comment by avinashpaliwal** [comment]
@sniklaus @deama Are you trying to run the [SepConv](https://github.com/sniklaus/pytorch-sepconv) CNN? Then just follow the usage instructions provided on the project page.

**Comment by sniklaus** [comment]
It looks like @deama is trying to load the SepConv weights into the Super Slo-Mo model. I am afraid that this is not possible, they are two different methods that are not compatible with each other. If you want to run SepConv, then I concur with @avinashpaliwal that you will have to follow the instructions in the SepConv repository: https://github.com/sniklaus/pytorch-sepconv

**Comment by deama** [comment]
Hmm, I see.
