### ISSUE TITLE
 Any information about the inference speed of this alg

### ISSUE THREAD

**Issue by butterl** [avinashpaliwal/Super-SloMo#18]
Hi， 
Thanks for sharing this awlsome project!

My friends have evaluated the sepconv ,the result is good but the inference is slow even on a PC. I do not got an available GPU at hand now（shared with someone else ）,so I'm not able to compare the two algs.  Any information about the inference speed of this alg？
Or any Chance that this Super-SloMo could run on a ARM64 Phone

Thanks

**Comment by avinashpaliwal** [comment]
Hi @butterl . I will add inference times for CPU/GPU soon, but it is comparatively very slow to run on CPU. For instance, while testing the [script](https://github.com/avinashpaliwal/Super-SloMo/blob/master/video_to_slomo.py) was able to interpolate around 8 frames/s on 1070 Max Q while it took around 45 seconds for it to interpolate 1 frame on i7-8750 at 720p.
