### ISSUE TITLE
Why not use OpenCV instead of ffmpeg?

### ISSUE THREAD

**Issue by NaxAlpha** [avinashpaliwal/Super-SloMo#19]
I want to ask why ffmpeg is being used instead of OpenCV's VideoCapture/VideoWriter etc? If there is no specific reason I can create a PR to implement OpenCV which will remove dependency from ffmpeg executable.

**Comment by avinashpaliwal** [comment]
I started using it as it was easier to pre-process the video for training. If there is not much difference in terms of video conversion to frames and vice versa times and quality then we'll remove the ffmpeg dependency. That would be great. Go ahead and create the PR.
