### ISSUE TITLE
How to do the evaluation?

### ISSUE THREAD

**Issue by jtetc** [avinashpaliwal/Super-SloMo#2]
Thanks for sharing!
How to try evaluation with my video file?

Thanks & Regards

**Comment by avinashpaliwal** [comment]
I will add a python script shortly.

**Comment by avinashpaliwal** [comment]
I have added the [video_to_slomo.py](https://github.com/avinashpaliwal/Super-SloMo/blob/master/video_to_slomo.py) script for video conversion.

**Comment by jtetc** [comment]
Thanks, @avinashpaliwal
