### ISSUE TITLE
ffmpeg problem 

### ISSUE THREAD

**Issue by lxy5513** [avinashpaliwal/Super-SloMo#20]
Hi, Thanks for your great project.

I got a problem, when handle the ffmpeg  
I conda install ffmpeg 
> conda install -c https://conda.anaconda.org/menpo ffmpeg   

the I run the script by --ffmpeg \`which ffmpeg\`   
> error: sh: 1: /home/xyliu/miniconda3/envs/DL/bin/ffmpeg/ffmpeg: not found . 

Could you please tell me how to fix it , thank you~

**Comment by deama** [comment]
The way I did it was to install ffmpeg without conda, just download it from the website, and then point the script to the install directory.

**Comment by lxy5513** [comment]
Thanks for you reply!
I download the ffmpeg and unzip it, than run as follow
`python video_to_slomo.py --ffmpeg ffmpeg --video /home/xyliu/projects/PPN/videos/test.mp4 --sf 3 --checkpoint SuperSloMo.ckpt --fps 90 --output output.mp4   
`
> ffmpeg/ffmpeg -i /home/xyliu/projects/PPN/videos/test.mp4 -vsync 0 -qscale:v 2 .tmpSuperSloMo/input/%06d.jpg
sh: 1: ffmpeg/ffmpeg: not found
Error converting file:/home/xyliu/projects/PPN/videos/test.mp4. Exiting.   

this is my ffmpeg folder: 
![image](https://user-images.githubusercontent.com/39720528/51008833-72f67200-1588-11e9-8689-15a0f6a3ee8a.png)

maybe i am some sort of fool. Could you please tell me how to solve it

**Comment by kokosandim** [comment]
I have a similar problem

```
FFmpeg\bin\ffmpeg\ffmpeg -i video.mp4 -vsync 0 -qscale:v 2 tmpSuperSloMo\input/%06d.jpg
The system cannot find the path specified.
Error converting file:video.mp4. Exiting.
```

i see this alert after entered that
`python video_to_slomo.py --ffmpeg FFmpeg\bin\ffmpeg --video video.mp4 --sf 2 --checkpoint checkpoint.ckpt --fps 60 --output output.mp4`

My project folder


![image](https://user-images.githubusercontent.com/12952533/51184427-ec6dc780-18dc-11e9-9ffe-b08be7bf389e.png)

I dont know which path is not right

**Comment by lxy5513** [comment]
Try it

--ffmpeg FFmpeg\bin

**Comment by kokosandim** [comment]
Thanks a lot, dear lxy5513 
its working I guess

![image](https://user-images.githubusercontent.com/12952533/51185202-25a73700-18df-11e9-9b22-a6e314b0ec42.png)

**Comment by avinashpaliwal** [comment]
I am closing this issue since it has been resolved.
