### ISSUE TITLE
About preparing training data

### ISSUE THREAD

**Issue by ChenxiTU** [avinashpaliwal/Super-SloMo#22]
Thank you for sharing your nice work!

I used create_dataset.py to build the training dataset as you mentioned.  But I find that 12 frames in each clip is not continuous. 

Maybe L.69 in create_dataset.py should be modified: 
`images = os.listdir(os.path.join(root, file)) ` -> `images = sorted(os.listdir(os.path.join(root, file)))`

Or I misunderstood, the frame in each clip should not be continuous?

**Comment by avinashpaliwal** [comment]
The frames inside a clip (folder) should be continuous. The clips can be in different order which doesn't affect the training because the network only looks at the frames from one particular clip. There is no need for sorted and it actually doesn't work because 11 is taken before 2. I have added zero padding using `%04d' [here](https://github.com/avinashpaliwal/Super-SloMo/blob/e8508bd949e51985ba73b99d0063090cec7e3679/data/create_dataset.py#L40) so that frames are named 0001.jpg, 0002.jpg and so on. But if you have more than 9999 frames, you'll have to increase the zero padding.

**Comment by ChenxiTU** [comment]
Thank you for your quickly reply. According to what you said, I think my understand is right.

What I'd like to say is that the frames inside a clip is not continuous when I used  create_dataset.py.
For example, in adobe240/train/0/, I got 12 frames like this: 0257.jpg, 0438.jpg, 1116.jpg ... which are not continuous.
If I add sorted(), in adobe240/train/0/, I got 12 frames: 0001.jpg, 0002.jpg, 0003.jpg ... 0012.jpg
I think sorted() can work because after extracted from video, frames' names are already padded.

Maybe different operating system has different result. In may case, I use ubuntu 16.04.

Sorry in advance, if I still misunderstand something.

**Comment by avinashpaliwal** [comment]
> Thank you for your quickly reply. According to what you said, I think my understand is right.
> 
> What I'd like to say is that the frames inside a clip is not continuous when I used create_dataset.py.
> For example, in adobe240/train/0/, I got 12 frames like this: 0257.jpg, 0438.jpg, 1116.jpg ... which are not continuous.
> If I add sorted(), in adobe240/train/0/, I got 12 frames: 0001.jpg, 0002.jpg, 0003.jpg ... 0012.jpg
> I think sorted() can work because after extracted from video, frames' names are already padded.
> 
> Maybe different operating system has different result. In may case, I use ubuntu 16.04.
> 
> Sorry in advance, if I still misunderstand something.

Ohh. I haven't tested it on Linux OSes yet. Thanks for pointing out the bug.

**Comment by avinashpaliwal** [comment]
> Hey, I want to know whether the images in one folder are really continues, or I just need to change the images' name by myself? The checkpoint trained by myself works really terrible, and is there anything to do with this bug?

Yes. The images inside 'clips' folders which contains 12 images should be continuous. If they are not, that would mess up the training. I have updated the dataset generation script. Try running it again to generate the whole dataset.
