### ISSUE TITLE
Is there anything wrong about the speed?

### ISSUE THREAD

**Issue by tingxueronghua** [avinashpaliwal/Super-SloMo#24]
**Describe the bug**

**To Reproduce**
e.g.
just run the video_to_slomo
my ffmpeg is built from source
and my pytorch is 1.0 with GPU

**Expected behavior**
there is something like "[04:25<3:00:25, 37.33s/it]"
and runs really slowly

**Additional context**
I don't think the version of pytorch caused the speed problem. 
So how fast you run this model?

**Comment by tingxueronghua** [comment]
Oh, i'm sorry. maybe this isn't a bug, but i don't know how to remove it...

**Comment by kokosandim** [comment]
I found maybe another some problem with speed. 
When I render video with parameters: sf = 2 and fps = 60fps, I get  a little shorter video than the original one. If original video is 17 sec then render video is 14 sec. I haven't figured out the problem yet.

**Comment by tingxueronghua** [comment]
also, I found some black blocks in the objects in motion. is there anyone else who also finds this?

**Comment by tianchi03** [comment]
> also, I found some black blocks in the objects in motion. is there anyone else who also finds this?

me 2.

**Comment by avinashpaliwal** [comment]
Try using the [eval.py](https://github.com/avinashpaliwal/Super-SloMo/blob/master/eval.py) script which uses openCV instead of ffmpeg. It is possible that the model can be improved by training on more diverse data, since adobe240fps is a limited dataset.

**Comment by kazenokizi** [comment]
@avinashpaliwal  Hello. I am wondering that whether it is right that an interpolation task of a 720p video from 30 fps to 60 fps will take over 15 minutes on a GPU? If so, is there any method that we can speed it up?

**Comment by avinashpaliwal** [comment]
> @avinashpaliwal Hello. I am wondering that whether it is right that an interpolation task of a 720p video from 30 fps to 60 fps will take over 15 minutes on a GPU? If so, is there any method that we can speed it up?

That really depends on the GPU and the length of the video.
