### ISSUE TITLE
How long train? or When finish train Epoch ?

### ISSUE THREAD

**Issue by escort94** [avinashpaliwal/Super-SloMo#25]
hello

I train super slomo .
When finish train Epoch ?

I am trainning Epoch 135.

thank you.

**Comment by escort94** [comment]
Self answer : 
"Epoch 199" finished train

Epoch:  198
 Loss: 13.000350  Iterations:   99/1533  TrainExecTime: 99.4  ValLoss:12.821774  ValPSNR: 30.4979  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.356719  Iterations:  199/1533  TrainExecTime: 75.0  ValLoss:12.819451  ValPSNR: 30.5012  ValEvalTime: 7.92 LearningRate: 0.000001
 Loss: 13.059358  Iterations:  299/1533  TrainExecTime: 74.9  ValLoss:12.819765  ValPSNR: 30.5010  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.048349  Iterations:  399/1533  TrainExecTime: 74.9  ValLoss:12.820006  ValPSNR: 30.5010  ValEvalTime: 7.91 LearningRate: 0.000001
 Loss: 12.855513  Iterations:  499/1533  TrainExecTime: 74.9  ValLoss:12.817331  ValPSNR: 30.5020  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.217664  Iterations:  599/1533  TrainExecTime: 75.0  ValLoss:12.820163  ValPSNR: 30.5013  ValEvalTime: 7.92 LearningRate: 0.000001
 Loss: 13.159157  Iterations:  699/1533  TrainExecTime: 74.9  ValLoss:12.822196  ValPSNR: 30.4989  ValEvalTime: 7.93 LearningRate: 0.000001
 Loss: 13.104509  Iterations:  799/1533  TrainExecTime: 75.0  ValLoss:12.820226  ValPSNR: 30.5014  ValEvalTime: 7.97 LearningRate: 0.000001
 Loss: 13.444480  Iterations:  899/1533  TrainExecTime: 75.0  ValLoss:12.820889  ValPSNR: 30.4989  ValEvalTime: 7.92 LearningRate: 0.000001
 Loss: 13.407564  Iterations:  999/1533  TrainExecTime: 75.0  ValLoss:12.821120  ValPSNR: 30.4996  ValEvalTime: 7.91 LearningRate: 0.000001
 Loss: 13.205854  Iterations: 1099/1533  TrainExecTime: 74.9  ValLoss:12.822172  ValPSNR: 30.4992  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.371440  Iterations: 1199/1533  TrainExecTime: 75.0  ValLoss:12.821109  ValPSNR: 30.4985  ValEvalTime: 7.97 LearningRate: 0.000001
 Loss: 13.313439  Iterations: 1299/1533  TrainExecTime: 74.9  ValLoss:12.821505  ValPSNR: 30.4963  ValEvalTime: 7.96 LearningRate: 0.000001
 Loss: 12.777627  Iterations: 1399/1533  TrainExecTime: 75.0  ValLoss:12.824670  ValPSNR: 30.4991  ValEvalTime: 7.93 LearningRate: 0.000001
 Loss: 13.095275  Iterations: 1499/1533  TrainExecTime: 74.9  ValLoss:12.824434  ValPSNR: 30.4954  ValEvalTime: 7.93 LearningRate: 0.000001
Epoch:  199
 Loss: 12.839095  Iterations:   99/1533  TrainExecTime: 99.5  ValLoss:12.823287  ValPSNR: 30.4983  ValEvalTime: 7.95 LearningRate: 0.000001
 Loss: 13.009885  Iterations:  199/1533  TrainExecTime: 74.9  ValLoss:12.822529  ValPSNR: 30.5003  ValEvalTime: 7.92 LearningRate: 0.000001
 Loss: 12.888221  Iterations:  299/1533  TrainExecTime: 75.0  ValLoss:12.820976  ValPSNR: 30.5024  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.258962  Iterations:  399/1533  TrainExecTime: 75.0  ValLoss:12.821937  ValPSNR: 30.5014  ValEvalTime: 7.91 LearningRate: 0.000001
 Loss: 13.225136  Iterations:  499/1533  TrainExecTime: 74.9  ValLoss:12.822439  ValPSNR: 30.5010  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 13.328113  Iterations:  599/1533  TrainExecTime: 74.9  ValLoss:12.821028  ValPSNR: 30.4995  ValEvalTime: 7.92 LearningRate: 0.000001
 Loss: 13.903210  Iterations:  699/1533  TrainExecTime: 75.0  ValLoss:12.819799  ValPSNR: 30.5001  ValEvalTime: 7.93 LearningRate: 0.000001
 Loss: 13.608873  Iterations:  799/1533  TrainExecTime: 75.0  ValLoss:12.823103  ValPSNR: 30.5001  ValEvalTime: 7.97 LearningRate: 0.000001
 Loss: 13.383028  Iterations:  899/1533  TrainExecTime: 74.9  ValLoss:12.822050  ValPSNR: 30.4996  ValEvalTime: 7.95 LearningRate: 0.000001
 Loss: 13.163999  Iterations:  999/1533  TrainExecTime: 75.1  ValLoss:12.822468  ValPSNR: 30.5001  ValEvalTime: 7.95 LearningRate: 0.000001
 Loss: 13.089723  Iterations: 1099/1533  TrainExecTime: 74.9  ValLoss:12.822032  ValPSNR: 30.4987  ValEvalTime: 7.97 LearningRate: 0.000001
 Loss: 12.768606  Iterations: 1199/1533  TrainExecTime: 74.9  ValLoss:12.821181  ValPSNR: 30.4998  ValEvalTime: 7.93 LearningRate: 0.000001
 Loss: 12.896706  Iterations: 1299/1533  TrainExecTime: 74.9  ValLoss:12.821431  ValPSNR: 30.5002  ValEvalTime: 7.94 LearningRate: 0.000001
 Loss: 12.946524  Iterations: 1399/1533  TrainExecTime: 74.9  ValLoss:12.822370  ValPSNR: 30.5009  ValEvalTime: 7.93 LearningRate: 0.000001
 Loss: 13.589174  Iterations: 1499/1533  TrainExecTime: 75.1  ValLoss:12.821481  ValPSNR: 30.5010  ValEvalTime: 7.93 LearningRate: 0.000001

(slomo) D:\slomo>

**Comment by tingxueronghua** [comment]
excuse me please, but what I got behind the "Iterations" was only 162, would you have any idea about that?

**Comment by tingxueronghua** [comment]
ummm, I really want to know whether you use the videos provided to make the dataset?

**Comment by avinashpaliwal** [comment]
> ummm, I really want to know whether you use the videos provided to make the dataset?

I didn't understand your question. Can you elaborate more?
