### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by lxy5513** [avinashpaliwal/Super-SloMo#28]
First of all, Thanks for your great work! 

when I run the video_to_slomo.py to slomo my costume video, The result is not good enough!  
I cut a little fragment , as follow:
![output](https://user-images.githubusercontent.com/39720528/52097591-9f8d2f00-2606-11e9-9de0-0564819ff06b.gif)

**Comment by lxy5513** [comment]
The origin video is [this](https://www.youtube.com/watch?v=iGKa0_mDcro) (25 FPS)
In docker, first run this   
`python video_to_slomo.py --ffmpeg /home/user/miniconda/envs/py36/bin --video videos/input/SuBingtian.mp4  --sf 3 --checkpoint SuperSloMo.ckpt --fps 75 --output videos/output/subingtian.mp4`

then run it, to expend video time to 3x.
`ffmpeg -i videos/output/subingtian.mp4 -filter:v "setpts=3.0*PTS" slow_subingtian.mp4`

Are there something wrong with me?  This video need to point out specify type?    
Do you have some advice? thanks in advance!

**Comment by fc695355831** [comment]
i have result like this.too. but the author's demo of car is perform well in my device and only the demo is work well ,so,i think probably the dataset of pretrain is weakly to generalization.look forward to the author's reply.

**Comment by avinashpaliwal** [comment]
The pretrained model has difficulty with large motions and as the resolution increases, the distance between corresponding pixels also increases. The model was trained on a limited dataset - which was publicly available - for comparison to the author's results. The author also uses a custom dataset (in addition to the adobe240fps dataset) of YouTube videos which are not publicly available. You can try training it on a custom dataset to improve it's performance.
