### ISSUE TITLE
Many visual artefacts

### ISSUE THREAD

**Issue by lagagne72** [avinashpaliwal/Super-SloMo#29]
Hello, I've tried this interesting script on my mac. It seems to generate a slowmo without any issues (slowly, but no errors), however the end result is full of artefacts like so:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5046739/52183550-1abe3300-2809-11e9-9d37-16b029d8a87b.gif)

I've tried with several videos and always got these blinking colors. Any ideas what I should try next? Thanks!

**Comment by kawakuboJin** [comment]
Hello,guys,I encountered this problom too. Has anybody solved this problem yet? 

this is my temp file below
![default](https://user-images.githubusercontent.com/25521522/52910902-29145080-32d9-11e9-9967-3f9710c7f483.png)

**Comment by avinashpaliwal** [comment]
Other users have also reported similar artifacts and I tried a temporary fix for CPU. I think for now you have to use the pretrained model as specified in the README or try training it from scratch on your device.
