### ISSUE TITLE
Freezing model possibility

### ISSUE THREAD

**Issue by arskama** [avinashpaliwal/Super-SloMo#30]
Hi,
Thanks first for the nice work you made!

feature request:
I was planning to try the result of your work on tensorflow.js
For this I need to convert the model from tensorflow to tensorflow.js, which means that I need to freeze the model before that.
Apparently, from what I found out, freezing the model means that I need to have at least the following data:
    --input_graph_def filename.pbtxt 
    --input_checkpoint filename.ckpt
    --output_node_names <name>
    --output_graph filename.pb 

see:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

At the moment, there is only the   --input_checkpoint filename.ckpt available.

**Describe the solution you'd like**
Is there a way you could upload the filename.pbtxt and output_node_names?

What do you think?
Thanks again!
Arno

**Comment by arskama** [comment]
For whatever reason, I just skipped the fact that you are using PyTorch!!!

**Comment by avinashpaliwal** [comment]
> For whatever reason, I just skipped the fact that you are using PyTorch!!!

Yes. So you will have to use some PyTorch to Tensorflow converter : )
