### ISSUE TITLE
scene change

### ISSUE THREAD

**Issue by xiaozhi2015** [avinashpaliwal/Super-SloMo#32]
When scene change occurs in a video, the inserted  frames are messes.
How to solve this situation? @avinashpaliwal 
Much thx!

**Comment by avinashpaliwal** [comment]
This behavior is expected as the model tries to interpolate between the boundary frames when scene change occurs. You have to manually cut the video at that point and run the script separately on two videos and combine them or cut the portion out after the video is generated using a video editing software.
