### ISSUE TITLE
The output video stutters every few seconds？

### ISSUE THREAD

**Issue by chwangteng** [avinashpaliwal/Super-SloMo#36]
The output video stutters every few seconds. When you slow the framerate in Pr or Final Cut Pro X，  it's utterly obvious, do you have this issue? I have tried different resolutiosns and bitrates，your mode and my model， but the problem still persists.

**Comment by avinashpaliwal** [comment]
Hi. In case the issue is not resolved, it is most likely due to duplicate frames getting generated by ffmpeg. This causes interpolation between static frames which looks like stuttering. You can also try using another opencv based video conversion script.
