### ISSUE TITLE
Audio in the output file?

### ISSUE THREAD

**Issue by natebluehooves** [avinashpaliwal/Super-SloMo#37]
Regarding specifically the use case where you increase framerate and don't slow down the video, I was wondering if an argument could be added to preserve the audio in the resulting video?

I'm actually finding this script does some really convincing work at increasing framerate and keeping things in real-time, but it strips the audio.

**Comment by avinashpaliwal** [comment]
You can lookup extracting audio and adding it to another video in ffmpeg. I think it will take some effort as the frame and audio timestamps won't match. I am not sure. You will have to try it out.
