### ISSUE TITLE
Compared to input the output size is changed

### ISSUE THREAD

**Issue by SJLNNU** [avinashpaliwal/Super-SloMo#38]
Hey guys ,
     I was trained a model used images with (1440,720) ,after i use the ckpt  with  video_to_slomo.py i got two type of images in tmpSuperSloMo/output folder one is (1440,720) another two are (1440,704)  ps the (--sf 3). I dont understand, where are the lost pixs?
     Another issue goes like this : my own dataset got the mean[0.696, 0.456, 0.957],and i changed the mean number in train.py  . After  I used the model created by train.py   ,i forgot to changed the mean number in video_to_slomo.py  which default[0.429, 0.431, 0.397],then i get some images in hidden tmpSuperSloMo/output folder . I compare  these images with the result images after i change the mean number in video_to_slomo.py.  They are totally same! !  Why mean parameter in video_to_slomo.py does not working? Did i misunderstand something? Please let me know.

**Comment by avinashpaliwal** [comment]
The model accepts dimensions in multiples of a number as it is an encoder decoder architecture with skip connections. Therefore, the images are resized before being passed to the model. The generated images are automatically resized back to the input dimensions by ffpmeg.

Changing the mean values may not create that much of a visual difference but might actually introduce some minor artifacts / a small drop in model's performance.
