### ISSUE TITLE
About the warpLoss computation.

### ISSUE THREAD

**Issue by musicrainie** [avinashpaliwal/Super-SloMo#39]
Why are g_I0_F_t_0 and g_I1_F_t_1 used for calculating warpLoss instead of g_I0_F_t_0_f and g_I0_F_t_0_f? Are there any theoretical reasons for that? I know it's consistent with the paper, but in which not so much detail exists explaining it. Looking forward to your opinion.

**Comment by avinashpaliwal** [comment]
From what I have observed I think the author was trying to train the first network to generate good optical flows. The second network adds small adjustments to this flow along with visibility maps. The visibility maps enforce the second network to ignore areas with less confidence from the warped images (g_I0_F_t_0_f and g_I0_F_t_0_f). This also causes the flow in those areas to be ignored as they are inconsequential to the final result (as those pixels are masked). This is just how I understand it and the actual reason might be something like this works better.

**Comment by musicrainie** [comment]
Thanks for your reply and I think your understanding is reasonable.
