### ISSUE TITLE
Clarification of results provided

### ISSUE THREAD

**Issue by beingkartik** [avinashpaliwal/Super-SloMo#45]
Hey, just wanted a few clarifications regarding the results provided in the Readme -

1) what do the results superslomo_adope240 mean? are these the test results on the adobe240 dataset? or is the network trained on just adobe240 dataset?
 

2) any idea why the results of superslomo are so much lower here compared to the paper ( 30 vs 33.14) , even though it is through the evaluation script provided by the authors?

**Comment by avinashpaliwal** [comment]
Hi,

1. The network was only trained using the adobe240 dataset.
2. The values are different because the evaluation script was updated by the author. The comparison logic was changed.
