### ISSUE TITLE
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by jackson1895** [avinashpaliwal/Super-SloMo#46]
Occurred an error during running video_to_slomo.py (pytorch 0.4.0  python3.6)

python video_to_slomo.py --video /path/to/video36.mp4  --sf 5 --checkpoint ../SuperSloMo.ckpt  --fps 60 --output ./results/output.mp4

The error log:
ffmpeg -i path/to/video36.mp4 -vsync 0 -qscale:v 2 .tmpSuperSloMo/input/%06d.jpg
ffmpeg version 4.0.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/ext/gaoliqing/video-caption/train-video/video36.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.13.100
  Duration: 00:00:11.04, start: 0.000000, bitrate: 496 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 320x240, 359 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x649ec80] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '.tmpSuperSloMo/input/%06d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 320x240, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  330 fps=0.0 q=2.0 Lsize=N/A time=00:00:11.01 bitrate=N/A speed=82.4x    
video:4311kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
  0%|                                                                                                                                | 0/329 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "video_to_slomo.py", line 216, in <module>
    main()
  File "video_to_slomo.py", line 165, in main
    flowOut = flowComp(torch.cat((I0, I1), dim=1))
  File "/home/xxx/anaconda3/envs/pytorch0.4.0_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/code/Super-SloMo-master/model.py", line 204, in forward
    x  = self.up1(x, s5)
  File "/home/xxx/anaconda3/envs/pytorch0.4.0_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxxx/code/Super-SloMo-master/model.py", line 130, in forward
    x = F.interpolate(x, scale_factor=2, mode='bilinear')
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'

looking forward to your reply, thanks!

**Comment by wenchaohu94** [comment]
use upsample（）or pytorch 0.4.1
