### ISSUE TITLE
How to save as a ckpt file after custom training is completed

### ISSUE THREAD

**Issue by ferretgeek** [avinashpaliwal/Super-SloMo#49]
I am not engaged in deep learning, but I really like this project. After I have trained the custom model, what code or method should I save as a ckpt file?

**Comment by MBadberg** [comment]
The checkpoints are created automatically at training and after. You should read the description again.
                                                                               
python train.py --dataset_root path\to\dataset --checkpoint_dir path\to\save\checkpoints
 __________________________________________________^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
