### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll' error when running video_to_slomo.py on Ubuntu 18.04

### ISSUE THREAD

**Issue by InterestingWalrus** [avinashpaliwal/Super-SloMo#5]
Hi, I'm trying to run the video_to_slomo.py script on ubuntu and I get the following error:

```
Traceback (most recent call last):
  File "video_to_slomo.py", line 199, in <module>
    main()
  File "video_to_slomo.py", line 95, in main
    ctypes.windll.kernel32.SetFileAttributesW(extractionDir, FILE_ATTRIBUTE_HIDDEN)
AttributeError: module 'ctypes' has no attribute 'windll'

```

I try to run the script using the following command: 

`python video_to_slomo.py --ffmpeg /usr/bin/ffmpeg --video ~/Super-SloMo/sample.mp4 --sf 4 --checkpoint checkpoint.ckpt --fps 240 --output output.mp4
`
Any ideas? I'm running on Ubuntu 18.04

**Comment by InterestingWalrus** [comment]
Commented out the line and seems to be working now

**Comment by wessyig** [comment]
hoE
