### ISSUE TITLE
Mulit-GPU Support

### ISSUE THREAD

**Issue by http403** [avinashpaliwal/Super-SloMo#52]
**Is your feature request related to a problem? Please describe.**
I'm training a very large dataset and I wish I can use some old GPU to speed up the process. Even a little bit.

**Describe the solution you'd like**
native Multi-GPU Support

**Describe alternatives you've considered**
I tried to implement myself but I'm totally lost as I have zero idea about deep learning and PyTorch

**Additional context**
N/A

**Comment by avinashpaliwal** [comment]
Currently there is no way for me to test this feature. You can try this [tutorial](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#create-model-and-dataparallel). I think you just have to add ```model = nn.DataParallel(model)``` to make it work.
