### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by rbrixel** [avinashpaliwal/Super-SloMo#53]
**Describe the bug**
After starting the script, the Error "cuDNN error: CUDNN_STATUS_EXECUTION_FAILED" appears and the script stops.

**To Reproduce**
1. Run the script

**Expected behavior**
It should generate a video :)

**Interpolated results/error output**
Full Output at the end.
`Traceback (most recent call last):
  File "video_to_slomo.py", line 216, in <module>
    main()
  File "video_to_slomo.py", line 165, in main
    flowOut = flowComp(torch.cat((I0, I1), dim=1))
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Programme\SuperSloMo\model.py", line 197, in forward
    x  = F.leaky_relu(self.conv1(x), negative_slope = 0.1)
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Device Used: GPU (nvidia rtx 2070)
 - Setup Info: Python 3.7; pytorch 1.1.0; py3.7_cuda90_cudnn7_1; cudatoolkit 9.0

**Additional context**
`(base) PS D:\Programme\SuperSloMo> python video_to_slomo.py --ffmpeg D:\Programme\ffmpeg\bin\ --video D:\in\C0093.mp4 --sf 4 --checkpoint D:\Programme\SuperSloMo\SuperSloMo.ckpt --fps 400 --output D:\out\400fps.mp4 --batch_size 1
D:\Programme\ffmpeg\bin\ffmpeg -i D:\in\C0093.mp4 -vsync 0 -qscale:v 2 tmpSuperSloMo\input/%06d.jpg
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000029f5c1c8d40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000029f5c1c8d40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\in\C0093.mp4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2018-07-28T16:48:54.000000Z
  Duration: 00:00:02.88, start: 0.000000, bitrate: 116527 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-4), 1920x1080 [SAR 1:1 DAR 16:9], 102672 kb/s, 100 fps, 100 tbr, 100k tbn, 200 tbc (default)
    Metadata:
      creation_time   : 2018-07-28T16:48:54.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2018-07-28T16:48:54.000000Z
      handler_name    : Sound Media Handler
    Stream #0:2(und): Data: none (rtmd / 0x646D7472), 819 kb/s (default)
    Metadata:
      creation_time   : 2018-07-28T16:48:54.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 04:23:13:92
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0000029f5c64d600] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'tmpSuperSloMo\input/%06d.jpg':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 100 fps, 100 tbn, 100 tbc (default)
    Metadata:
      creation_time   : 2018-07-28T16:48:54.000000Z
      handler_name    : Video Media Handler
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  288 fps=175 q=2.0 Lsize=N/A time=00:00:02.88 bitrate=N/A speed=1.75x
video:30649kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
  0%|                                                                                          | 0/287 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "video_to_slomo.py", line 216, in <module>
    main()
  File "video_to_slomo.py", line 165, in main
    flowOut = flowComp(torch.cat((I0, I1), dim=1))
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Programme\SuperSloMo\model.py", line 197, in forward
    x  = F.leaky_relu(self.conv1(x), negative_slope = 0.1)
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Programme\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

**Comment by avinashpaliwal** [comment]
Try using pytorch 0.4.1 and CUDA 9.2.

**Comment by avinashpaliwal** [comment]
Duplicate issue  #55
