### ISSUE TITLE
Hey! Just found out that your repository copies code from mine. Can I get credits? Thank you!

### ISSUE THREAD

**Issue by TheFairBear** [avinashpaliwal/Super-SloMo#61]
Hello Avinash! 
I just randomly stumbled onto this repository. It was weird to find out that you have copied most of the working code from my repository https://github.com/TheFairBear/Super-SlowMo. Can I please get credits? Thank you!

**Comment by avinashpaliwal** [comment]
Yes, I did use your code as base mostly in the train.py. But I also added things from scratch trying to get the network to converge and make the repository more accessible. I have added your repository in the references. Thanks for your work!
