### ISSUE TITLE
UCF101_results

### ISSUE THREAD

**Issue by jian3xiao** [avinashpaliwal/Super-SloMo#63]
I have download your UCF101_results, there said " Interpolation results on UCF101 of DVF, SepConv, SuperSloMo trained on Adobe240fps, and SuperSloMo trained on YouTube240fps andAdobe240fps " In README. 
Do you train your own DVF model on Adobe240fps? In original DVF code, the model is trainde on UCF101 images with 256x256 size. If you train your own DVF model, you use 256x256 images on Adobe240fps?

And in your paper, comparison with DVF, SepConv on UCF101 without Adobe240fps. Why did compare different methods on Adobe240fps?

And I confuse that different paper train they model on different dataset, for example, DVF train on UCF101, SepConv train on videos from YouTube. How compare these methods fairly？

**Comment by avinashpaliwal** [comment]
Hi!
First, this repo is an implementation of a paper by [Huaizu Jiang](https://people.cs.umass.edu/~hzjiang/). The UCF101 results that you downloaded are provided by Huaizu on his project page. I am assuming that he uses the publicly available GitHub repos for those results. 
The adobe240 dataset is comparison is used for ablation studies and to show that having more samples(youtube) is helpful in improving the performance. And for fairness, I think the paper has results on multiple different datasets.

**Comment by jian3xiao** [comment]
thanks ！
