### ISSUE TITLE
Cannot reproduce your results  on UCF101 dataset.

### ISSUE THREAD

**Issue by chuchienshu** [avinashpaliwal/Super-SloMo#67]
**Describe the bug**
Hi @avinashpaliwal , Thanks for sharing this awesome work! However, I cannot reproduce the performance that you released:   

> pretrained mine	29.77	0.874	15.58

What I got is  

>  PSNR: 24.54, SSIM: 0.762, IE: 24.64

The result obtained by **get_results_bug_fixed.sh** script.
It's much worse than yours. And I have no idea what is going wrong.

**To Reproduce**
The complete script can be found [here](https://gist.github.com/chuchienshu/aa7e9a98fb4db54c124f7813a28d7fa5). So it's easily to reproduce this Bug. In fact, I just adapted part of your code to perform single frame interpolation.

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Device Used: GPU
 - Setup Info:  PyTorch 0.4.1, Python 3.5.2

Any suggestion would be appreciated. Thanks in advance!

**Comment by georgeandrei1998** [comment]
Hi @chuchienshu, did you find the solution? I have the same problem. 
I took your script for single frame interpolation and after I ran get_results_bug_fixed.sh script I obtained similar results with yours.
