### ISSUE TITLE
in create_data.py, Error converting file

### ISSUE THREAD

**Issue by YongTaekLee** [avinashpaliwal/Super-SloMo#71]
**Describe the bug**
I try to convert video to frame by using ffmpeg.
however i have "print" that it is Error converting file:(filename). Exiting.
I download dataset in your github url, then why this error apear??
is it okay that I ignore this error ?
**To Reproduce**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Device Used [GPU]
 - Setup Info [ PyTorch 1.2, Python 3.6, ]

**Comment by avinashpaliwal** [comment]
Hi @YongTaekLee. You will have to provide more details like the exact error message. Add a log from your terminal here.

**Comment by CauchyHu** [comment]
I'm also getting this error in video_to_slomo
![image](https://user-images.githubusercontent.com/25081842/89395261-aaff7000-d73f-11ea-9720-b9270a7cdd54.png)

**Comment by CauchyHu** [comment]
I‘ve solved this error 
![image](https://user-images.githubusercontent.com/25081842/89398969-61655400-d744-11ea-9ba9-ee846d9fd224.png)
Note that the path in the box in the figure is correct
