### ISSUE TITLE
How to output slowMo video using video_to_slomo.py

### ISSUE THREAD

**Issue by Microos** [avinashpaliwal/Super-SloMo#72]
Hi, thank you for such an amazing work of super slo-mo!

I have successfully gone through the `video_to_slomo.py` and got the output video from 30 fps to 90 fps. My input video is a 10-second one, however, the output one is still 10 seconds long, it is just playing at 90fps instead of 30. 
So my question would be, are there any flags I should set up in [video_to_slomo.py: 80](https://github.com/avinashpaliwal/Super-SloMo/blob/a3be3dbc363f48f2cdaafc7224597dbd5a0d9370/video_to_slomo.py#L80) to make sure the output video is 3x longer than the input one but both of them playing in 30 fps?

**Comment by Thomasedv** [comment]
You set how many times you want to multiply the frames with the `--sf` , and the `--fps` flag says how many frames per second in the output video. 

So you need to think of input video at 30 fps, you want to triple it to 90 frames per second, `--sf 3`, and the output framerate should be 30, such that the playback will be 3 times longer than the input, in this case 30 seconds. `--fps 30`

**Comment by Microos** [comment]
> You set how many times you want to multiply the frames with the `--sf` , and the `--fps` flag says how many frames per second in the output video.
> 
> So you need to think of input video at 30 fps, you want to triple it to 90 frames per second, `--sf 3`, and the output framerate should be 30, such that the playback will be 3 times longer than the input, in this case 30 seconds. `--fps 30`

Oh! I got it. I thought `--fps` is a flag for the network, so I didn't change it. Thank you!
