### ISSUE TITLE
[Asking for help] about output format and size

### ISSUE THREAD

**Issue by Nika-m** [avinashpaliwal/Super-SloMo#77]
hello, I converted 00:01sec video 1280x720 30fps 2mb size video to (--sf 3 --fps90) and it gave me output in mkv format of 187mb size, 6 second 30fps video took about 960mb, on 120fps. isn't it too much? can I output any other format? why is it such a large .mkv
2.I tried to convert that mkv video using software "Handbrake" and it did convert in about 3-4 seconds 
and video was about 8mb in mp4 format 
if there is any way to output smaller videos please tell me

**Comment by wagawaga4k** [comment]
yeah.. i suddenly had a 2.7gb mkv file in output folder (27seconds 1080p) :D

**Comment by Thomasedv** [comment]
Videos are just all the images stitched together, using Handbrake as you did, or by adjusting the command run to create the file in `video_to_slomo.py`. For example i use something like this:

`{} -r {} -i {}/%d.png -b:v 10M -crf 30 {}`

However i convert to webm files, so you might need to specify the codec to be used. Lowering the the 10M will lower the size. 

Changed this line: 
https://github.com/avinashpaliwal/Super-SloMo/blob/a3be3dbc363f48f2cdaafc7224597dbd5a0d9370/video_to_slomo.py#L80

**Comment by MatteCrystal** [comment]
I would like to output as mp4 as well but i'm not familiar with the coding needed to do that. does anyone know the actual code needed to change it to mp4. 

Also if the output can be changed why is this not an optional argument? being able to do something like --exe mp4 would be really nice.

**Comment by Thomasedv** [comment]
I think it's simply because it's much more effort than the creators want to put into it. If the output format matters, you can deal with that yourself pretty easily, they are using a program called ffmpeg and changing the command for that isn't too hard, and lets you convert the interpolated images to pretty much any video format you want. The script creator basically make a near if not entirely lossless video conversion, and it's more up to the users to adjust that to their needs.

**Comment by avinashpaliwal** [comment]
@Thomasedv is right. 1) The effort is too high to support different formats. 2) Size can be reduced by switching the format and using the crf flag in ffmpeg which sets the compression level. 3) The time to generate video mostly depends on your system running the CNN.
Therefore you can lookup ffmpeg online and either convert the generated video or modify the ffmpeg command in the script.
