### ISSUE TITLE
output needs to have mkv container

### ISSUE THREAD

**Issue by tapsys** [avinashpaliwal/Super-SloMo#79]
**Describe the bug**
basically: output needs to have mkv container

when i try: "python video_to_slomo.py --ffmpeg C:\Users\edwar\Desktop\slow\ffmpeg\bin --video C:\Users\edwar\Desktop\slow\input\ni.mp4 --sf 4
 --checkpoint C:\Users\edwar\Desktop\slow\prog\SuperSloMo.ckpt --fps 120 --output C:\Users\edwar\Desktop\slow\output\ni120.mp4"

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Setup Info [conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev, Python 3.7, ]

**Comment by quintendewilde** [comment]
I also have this issue on OS: MacOS
