### ISSUE TITLE
I cant't save the slomo video

### ISSUE THREAD

**Issue by Julyliying** [avinashpaliwal/Super-SloMo#8]
Hi, thanks for your sharing.
When I test the video_to_slomo.py, I can't save the slomo video.And there is some limit for the size of the input video? My input video's size is 1280*720.The commandline show:
[swscaler @ 0x3b3a5e0] deprecated pixel format used, make sure you did set range correctly
Past duration 0.999992 too large
    Last message repeated 1 times
Input stream #0:0 frame changed from size:1280x704 fmt:yuvj420p to size:1280x720 fmt:yuvj420p
Input stream #0:0 frame changed from size:1280x720 fmt:yuvj420p to size:1280x704 fmt:yuvj420p
[swscaler @ 0x39ded20] deprecated pixel format used, make sure you did set range correctly
Input stream #0:0 frame changed from size:1280x704 fmt:yuvj420p to size:1280x720 fmt:yuvj420p
Input stream #0:0 frame changed from size:1280x720 fmt:yuvj420p to size:1280x704 fmt:yuvj420p
[swscaler @ 0x12ea680] deprecated pixel format used, make sure you did set range correctly

**Comment by shadowzoom** [comment]
Hi @Julyliying ! How you fix it? I have Past duration 0.999992 too large too
