### ISSUE TITLE
How can I find the dataset of 240-fps video from YouTube

### ISSUE THREAD

**Issue by Zhang-Hu927** [avinashpaliwal/Super-SloMo#88]
Hi, thanks your code.Can you send me your dataset of 240-fps video from YouTube

**Comment by avinashpaliwal** [comment]
Unfortunately, I cannot share the dataset. You can try the dataset here: http://toflow.csail.mit.edu/

**Comment by basilevh** [comment]
Hi,
If the dataset still cannot be published, I would be interested in knowing how the scraping process worked? Does YouTube even support high frame rate videos beyond 60 FPS? Are there any tips or tricks that you might be able to share?
Thank you!
