### ISSUE TITLE
ModuleNotFoundError: No module named 'model' and 'dataloder'

### ISSUE THREAD

**Issue by 12ben** [avinashpaliwal/Super-SloMo#9]
Where can I find them? 
dataloader isn't from torch.
Thanks a lot.

**Comment by eng100200** [comment]
already a dataloader file is provided
howwever, i have one question @12ben ,,,how to run the ipynb file in the linux terminal,,,,i know for python i use >>> python filename.py and run

**Comment by 12ben** [comment]
> 
> 
> already a dataloader file is provided
> howwever, i have one question @12ben ,,,how to run the ipynb file in the linux terminal,,,,i know for python i use >>> python filename.py and run

https://github.com/avinashpaliwal/Super-SloMo/issues/6

**Comment by eng100200** [comment]
@12ben  what is this link for??
